name: Used By
description: Generate Used By badge from GitHub dependents information.
author: shenxianpeng
branding:
  icon: "thumbs-up"
  color: "green"
inputs:
  repo:
    description: >-
      GitHub repository name. e.g. shenxianpeng/used-by. Defaults to shenxianpeng/used-by.
    required: true
    default: 'shenxianpeng/used-by'
  doc-type:
    description: >-
      Supports md(Markdown) and rst(reStructuredText). Defaults to `md`.
    required: false
    default: 'md'
  badge-label:
    description: >
      The badge display name. Defaults to `Used by`.
    required: false
    default: 'Used by'
  badge-color:
    description: The badge display color. Defaults to `informational`.
    required: false
    default: 'informational'
  badge-logo:
    description: The badge display color. Defaults to `slickpic`.
    required: false
    default: "slickpic"
  update-badge:
    description: The badge display color. Defaults to `false`.
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Install used-by
      shell: bash
      run: pip install git+https://github.com/shenxianpeng/used-by.git@main

    - name: Run used-by
      id: used-by
      shell: bash
      run: |
        used-by \
         --repo="${{ inputs.repo }}" \
         --file-path="${{ inputs.file-path }}"" \
         --badge-label="${{ inputs.badge-label }}" \
         --badge-color="${{ inputs.badge-color }}"" \
         --badge-logo="${{ inputs.badge-logo }}"" \
         --update-badge=${{ inputs.update-badge }}
