# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.py"
      - "**requirements*.txt"
      - pyproject.toml
      - .pre-commit-config.yaml
      - ".github/workflows/build.yml"
      - "!docs/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build wheel
        run: python -m pip wheel -w dist .

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: used-by_wheel
          path: dist/*.whl
