# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Upload Python Package

on:
  release:
    branches: [main]
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    uses: shenxianpeng/.github/.github/workflows/py-publish.yml@main
    secrets: inherit
